name: Waka Readme

on:
  schedule:
    # Runs at 1am IST every 5th day of month
    - cron: '0 1 */5 * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          #COMMIT_USERNAME: "MaureenDadap"
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_PROFILE_VIEWS: "False"
          #SHOW_OS: "False"
          SHOW_LOC_CHART: "False"
